(import tools/set)
(use spork/test)

(start-suite)
(assert (= (set/new 1) (set/new 1)))
(assert (not= (set/new 1) (set/new 1 2)))
(assert (not= (set/new 1) (set/new 2)))

(assert (< (set/new 1) (set/new 1 2)))
(assert (= (set/union (set/new 1)
                      (set/new 2))
           (set/new 1 2)))
(assert (= (set/intersection (set/new 1 2)
                             (set/new 2 3))
           (set/new 2)))
(assert (= (set/difference (set/new 1 2)
                           (set/new 2 3))
           (set/new 1)))
(assert (= (set/difference (set/new 1 2)
                           (set/new 2 3)
                           (set/new 1))
           (set/new)))
(assert (= (set/symmetric-difference (set/new 1 2)
                                     (set/new 2 3))
           (set/new 1 3)))
(assert (= (set/clone (set/new 1))
           (set/new 1)))
(let [set1 (set/new 1)
      set2 (set/clone set1)]
  (set/add set1 2)
  (assert (not= set1 set2))
  (assert (= set1 (set/new 1 2)))
  (set/remove set1 2)
  (assert (= set1 set2))
  (set/remove set1 1)
  (set/remove set2 1)
  (assert (= set1 set2)))
(end-suite)
